# Automatically generated by pb2py
from __future__ import absolute_import
from .. import protobuf as p


class WipeDevice(p.MessageType):
    FIELDS = {
        1: ('force', p.BoolType, 0),
    }
    MESSAGE_WIRE_TYPE = 5
